_homepage:
    pattern: /
    defaults: { _controller: AppBundle:Default:index }

_jd2:
    pattern: /jd2
    defaults: { _controller: AppBundle:Default:jd2 }

_e1:
    pattern: /e1
    defaults: { _controller: AppBundle:Event:e }
